$(document).ready(function(){
    $('.bar1gr1').attr('hidden','hidden');
    $('.bar1gr2').attr('hidden','hidden');
    $('.bar1gr3').attr('hidden','hidden');
    $('.bar0gr1').attr('hidden','hidden');
    $('#graph1').attr('hidden','hidden');
    $('.opcio1').attr('hidden','hidden');
    $('#fond').attr('hidden','hidden');
    $('.butgrap').attr('hidden','hidden');
    $('.butgrap2').attr('hidden','hidden');
    $('.fl2').attr('hidden','hidden');
    $('.fl1').attr('hidden','hidden');
    $('.fl3').attr('hidden','hidden');
    $('.fl4').attr('hidden','hidden');
    $('.eja').attr('hidden','hidden');
    $('.est1').attr('hidden','hidden');
    $('.est2').attr('hidden','hidden');
    $('.est3').attr('hidden','hidden');
    

    $("#ej1").mouseenter(function(){
        $("#lap4").removeAttr("hidden");
        $("#ej4").removeAttr("hidden");
        });
        $("#ej1").mouseleave(function(){
            $("#lap4").attr('hidden','hidden');
            $("#ej4").attr('hidden','hidden');
            });
    $("#lap1").mouseenter(function(){
        $("#lap4").removeAttr("hidden");
        $("#ej4").removeAttr("hidden");
        });
    $("#lap1").mouseleave(function(){
        $("#lap4").attr('hidden','hidden');
        $("#ej4").attr('hidden','hidden');
        });
    $("#lap4").click(function(){
        $("#graph1").removeAttr("hidden");
        $(".bar0gr1").removeAttr("hidden");
        $(".opcio").attr('hidden','hidden');
        $(".opcio1").attr('hidden','hidden');
        $("#fond").removeAttr("hidden");
        $('.butgrap').removeAttr("hidden");
        $(".fl1").removeAttr("hidden");
        $("#ej1").attr('hidden','hidden');
                $("#ej2").attr('hidden','hidden');
                $("#ej3").attr('hidden','hidden');
                $(".eja").attr('hidden','hidden');
        });
        $("#lap1").click(function(){
            $("#graph1").removeAttr("hidden");
            $(".bar0gr1").removeAttr("hidden");
            $(".opcio").attr('hidden','hidden');
            $(".opcio1").attr('hidden','hidden');
            $("#fond").removeAttr("hidden");
            $('.butgrap').removeAttr("hidden");
            $(".fl1").removeAttr("hidden");
            $("#ej1").attr('hidden','hidden');
                $("#ej2").attr('hidden','hidden');
                $("#ej3").attr('hidden','hidden');
                $(".eja").attr('hidden','hidden');
            });
            $("#ej1").click(function(){
                $("#graph1").removeAttr("hidden");
                $(".bar0gr1").removeAttr("hidden");
                $(".opcio").attr('hidden','hidden');
                $(".opcio1").attr('hidden','hidden');
                $("#fond").removeAttr("hidden");
                $('.butgrap').removeAttr("hidden");
                $(".fl1").removeAttr("hidden");
                $("#ej1").attr('hidden','hidden');
                $("#ej2").attr('hidden','hidden');
                $("#ej3").attr('hidden','hidden');
                $(".eja").attr('hidden','hidden');
                $(".est1").attr('hidden','hidden');
                });
                $("#ej4").click(function(){
                    $("#graph1").removeAttr("hidden");
                    $(".bar0gr1").removeAttr("hidden");
                    $(".opcio").attr('hidden','hidden');
                    $(".opcio1").attr('hidden','hidden');
                    $("#fond").removeAttr("hidden");
                    $('.butgrap').removeAttr("hidden");
                    $(".fl1").removeAttr("hidden");
                    $("#ej1").attr('hidden','hidden');
                $("#ej2").attr('hidden','hidden');
                $("#ej3").attr('hidden','hidden');
                $(".eja").attr('hidden','hidden');
                    });
    $("#lap2").mouseenter(function(){
        $("#lap5").removeAttr("hidden");
        $("#ej5").removeAttr("hidden");
        });
    $("#lap2").mouseleave(function(){
        $("#lap5").attr('hidden','hidden');
        $("#ej5").attr('hidden','hidden');
    });
    $("#lap2").click(function(){
        $(location).attr('href',"efecarthe1.html");
    });
    $("#lap5").click(function(){
        $(location).attr('href',"efecarthe1.html");
        
    });
    $("#ej2").click(function(){
        $(location).attr('href',"efecarthe1.html");
    });
    $("#ej5").click(function(){
        $(location).attr('href',"efecarthe1.html");
    });
    $("#lap3").mouseenter(function(){
        $("#lap6").removeAttr("hidden");
        $("#ej6").removeAttr("hidden");
        });
    $("#lap3").mouseleave(function(){
        $("#lap6").attr('hidden','hidden');
        $("#ej6").attr('hidden','hidden');
        });
    $("#lap3").click(function(){
        $(location).attr('href',"efecarthe2.html");
        
    });
    $("#lap6").click(function(){
        $(location).attr('href',"efecarthe2.html");
        
    });
    $("#ej6").click(function(){
        $(location).attr('href',"efecarthe2.html");
        
    });
    $("#ej3").click(function(){
        $(location).attr('href',"efecarthe2.html");
        
    });

    $("#bl01gr1").mouseenter(function(){
        $("#blo1gr1").removeAttr("hidden");
        $("#arc1").removeAttr("hidden");
        $("#ard1").removeAttr("hidden");
        $("#por1").removeAttr("hidden");
        $("#par1").removeAttr("hidden");
    });
    $("#bl01gr1").mouseleave(function(){
        $("#blo1gr1").attr('hidden','hidden');
        $('.fl2').attr('hidden','hidden');
        $('#por1').attr('hidden','hidden');
        $('#par1').attr('hidden','hidden');
        });

    $("#bl02gr1").mouseenter(function(){
        $("#blo2gr1").removeAttr("hidden");
        $("#arc2").removeAttr("hidden");
        $("#ard2").removeAttr("hidden");
        $("#por2").removeAttr("hidden");
        $("#par2").removeAttr("hidden");
        });
    $("#bl02gr1").mouseleave(function(){
        $("#blo2gr1").attr('hidden','hidden');
        $('.fl2').attr('hidden','hidden');
        $('#por2').attr('hidden','hidden');
        $('#par2').attr('hidden','hidden');
        });

    $("#bl03gr1").mouseenter(function(){
        $("#blo3gr1").removeAttr("hidden");
        $("#arc3").removeAttr("hidden");
        $("#ard3").removeAttr("hidden");
        $("#por3").removeAttr("hidden");
        $("#par3").removeAttr("hidden");
        });
    $("#bl03gr1").mouseleave(function(){
        $("#blo3gr1").attr('hidden','hidden');
        $('.fl2').attr('hidden','hidden');
        $('#por3').attr('hidden','hidden');
        $('#par3').attr('hidden','hidden');
        });
    
    $("#bl04gr1").mouseenter(function(){
        $("#blo4gr1").removeAttr("hidden");
        $("#arc4").removeAttr("hidden");
        $("#ard4").removeAttr("hidden");
        $("#por4").removeAttr("hidden");
        $("#par4").removeAttr("hidden");
        });
    $("#bl04gr1").mouseleave(function(){
        $("#blo4gr1").attr('hidden','hidden');
        $('.fl2').attr('hidden','hidden');
        $('#por4').attr('hidden','hidden');
        $('#par4').attr('hidden','hidden');
    });

        $("#bl01gr2").mouseenter(function(){
            $("#blo1gr2").removeAttr("hidden");
            $("#brc1").removeAttr("hidden");
            $("#brd1").removeAttr("hidden");
            $("#por11").removeAttr("hidden");
            $("#par11").removeAttr("hidden");
            });
        $("#bl01gr2").mouseleave(function(){
            $("#blo1gr2").attr('hidden','hidden');
            $('.fl3').attr('hidden','hidden');
            $('.est2').attr('hidden','hidden');
            });
    
        $("#bl02gr2").mouseenter(function(){
            $("#blo2gr2").removeAttr("hidden");
            $("#brc2").removeAttr("hidden");
            $("#brd2").removeAttr("hidden");
            $("#por21").removeAttr("hidden");
            $("#par21").removeAttr("hidden");
            });
        $("#bl02gr2").mouseleave(function(){
            $("#blo2gr2").attr('hidden','hidden');
            $('.fl3').attr('hidden','hidden');
            $('.est2').attr('hidden','hidden');
            });
    
        $("#bl03gr2").mouseenter(function(){
            $("#blo3gr2").removeAttr("hidden");
            $("#brc3").removeAttr("hidden");
            $("#brd3").removeAttr("hidden");
            $("#por31").removeAttr("hidden");
            $("#par31").removeAttr("hidden");
            });
        $("#bl03gr2").mouseleave(function(){
            $("#blo3gr2").attr('hidden','hidden');
            $('.fl3').attr('hidden','hidden');
            $('.est2').attr('hidden','hidden');
            });
        
        $("#bl04gr2").mouseenter(function(){
            $("#blo4gr2").removeAttr("hidden");
            $("#brc4").removeAttr("hidden");
            $("#brd4").removeAttr("hidden");
            $("#por41").removeAttr("hidden");
            $("#par41").removeAttr("hidden");
            });
        $("#bl04gr2").mouseleave(function(){
            $("#blo4gr2").attr('hidden','hidden');
            $('.fl3').attr('hidden','hidden');
            $('.est2').attr('hidden','hidden');
        });



        $("#bl01gr3").mouseenter(function(){
            $("#blo1gr3").removeAttr("hidden");
            $("#crc1").removeAttr("hidden");
            $('#cra1').attr('hidden','hidden');
            $("#por12").removeAttr("hidden");
        });
        $("#bl01gr3").mouseleave(function(){
            $("#blo1gr3").attr('hidden','hidden');
            $('.fl4').attr('hidden','hidden');
            $("#cra1").removeAttr("hidden");
            $('.est3').attr('hidden','hidden');
            });
    
        $("#bl02gr3").mouseenter(function(){
            $("#blo2gr3").removeAttr("hidden");
            $("#crc2").removeAttr("hidden");
            $('#cra2').attr('hidden','hidden');
            $("#por22").removeAttr("hidden");
            });
        $("#bl02gr3").mouseleave(function(){
            $("#blo2gr3").attr('hidden','hidden');
            $('.fl4').attr('hidden','hidden');
            $("#cra2").removeAttr("hidden");
            $('.est3').attr('hidden','hidden');
            });
    
        $("#bl03gr3").mouseenter(function(){
            $("#blo3gr3").removeAttr("hidden");
            $("#crc3").removeAttr("hidden");
            $('#cra3').attr('hidden','hidden');
            $("#por32").removeAttr("hidden");
            });
        $("#bl03gr3").mouseleave(function(){
            $("#blo3gr3").attr('hidden','hidden');
            $('.fl4').attr('hidden','hidden');
            $("#cra3").removeAttr("hidden");
            $('.est3').attr('hidden','hidden');
            });
        $("#bl04gr3").mouseenter(function(){
            $("#blo4gr3").removeAttr("hidden");
            $("#crc4").removeAttr("hidden");
            $('#cra4').attr('hidden','hidden');
            $("#por42").removeAttr("hidden");
            });
        $("#bl04gr3").mouseleave(function(){
            $("#blo4gr3").attr('hidden','hidden');
            $('.fl4').attr('hidden','hidden');
            $("#cra4").removeAttr("hidden");
            $('.est3').attr('hidden','hidden');
        });
        $("#bl05gr3").mouseenter(function(){
            $("#blo5gr3").removeAttr("hidden");
            $("#crc5").removeAttr("hidden");
            $('#cra5').attr('hidden','hidden');
            $("#por52").removeAttr("hidden");
            });
        $("#bl05gr3").mouseleave(function(){
            $("#blo5gr3").attr('hidden','hidden');
            $('.fl4').attr('hidden','hidden');
            $("#cra5").removeAttr("hidden");
            $('.est3').attr('hidden','hidden');
        });
        $("#bl06gr3").mouseenter(function(){
            $("#blo6gr3").removeAttr("hidden");
            $("#crc6").removeAttr("hidden");
            $('#cra6').attr('hidden','hidden');
            $("#por62").removeAttr("hidden");
            });
        $("#bl06gr3").mouseleave(function(){
            $("#blo6gr3").attr('hidden','hidden');
            $('.fl4').attr('hidden','hidden');
            $("#cra6").removeAttr("hidden");
            $('.est3').attr('hidden','hidden');
        });
        



        $(".butgrap").mouseenter(function(){
            $(".butgrap2").removeAttr("hidden");
            });
        $(".butgrap").mouseleave(function(){
            $(".butgrap2").attr('hidden','hidden');
        });
        $("#butgr2").mouseenter(function(){
            $(".butgrap2").removeAttr("hidden");
            });
        $("#butgr2").mouseleave(function(){
            $(".butgrap2").attr('hidden','hidden');
        });
        $("#butgr3").mouseenter(function(){
            $(".butgrap2").removeAttr("hidden");
            });
        $("#butgr3").mouseleave(function(){
            $(".butgrap2").attr('hidden','hidden');
        });
        $("#butgr1").click(function(){
            $(location).attr('href',"efecarthe.html");
        });
        $("#butgr2").click(function(){
            $(location).attr('href',"efecarthe.html");
        });
        $("#butgr3").click(function(){
            $(location).attr('href',"efecarthe.html");
        });
        $(".butgrap2").click(function(){
            $(location).attr('href',"efecarthe.html");
        });

        });