$(document).ready(function(){
    $('#bidib').attr('hidden','hidden');
    $('#tridib').attr('hidden','hidden');
    $('.bidimen').attr('hidden','hidden');
    $('.tridimen').attr('hidden','hidden');
    $('.tridic').attr('hidden','hidden');
    $('#bidic').attr('hidden','hidden');
    $('#gale2').attr('hidden','hidden');
    $("#arbi1").attr('hidden','hidden');
    $("#artri1").attr('hidden','hidden');
    $("#brtri1").attr('hidden','hidden');
    $('.vuel').attr('hidden','hidden');
    $('.texa').attr('hidden','hidden');
    $('#tex4').attr('hidden','hidden');
    

    $("#gale1").mouseenter(function(){
        $("#gale2").removeAttr("hidden");
        });
    $("#gale1").mouseleave(function(){
        $("#gale2").attr('hidden','hidden');
        });
    $("#gale1").click(function(){
        $(location).attr('href',"galearthe.html");
    });
    $("#gale2").click(function(){
        $(location).attr('href',"galearthe.html");
    });

    $("#bidi0").mouseenter(function(){
        $("#bidib").removeAttr("hidden");
        $("#arbi1").removeAttr("hidden");
        });
    $("#bidi0").mouseleave(function(){
        $("#bidib").attr('hidden','hidden');
        $("#arbi1").attr('hidden','hidden');
        });
    $("#bidib").click(function(){
        $('.bidimen').removeAttr('hidden');
        $('.dimain').attr('hidden','hidden');
        $('.disec').attr('hidden','hidden');
        $('#vuel1').removeAttr('hidden');
        $('.texa').removeAttr('hidden');
    });
    $("#bidi0").click(function(){
        $('.bidimen').removeAttr('hidden');
        $('.dimain').attr('hidden','hidden');
        $('.disec').attr('hidden','hidden');
        $('#vuel1').removeAttr('hidden');
        $('.texa').removeAttr('hidden');
    });
    $("#arbi").click(function(){
        $('.bidimen').removeAttr('hidden');
        $('.dimain').attr('hidden','hidden');
        $('.disec').attr('hidden','hidden');
        $('#vuel1').removeAttr('hidden');
        $('.texa').removeAttr('hidden');
    });
    $("#bidia").mouseenter(function(){
        $("#bidic").removeAttr("hidden");
        });
    $("#bidia").mouseleave(function(){
        $("#bidic").attr('hidden','hidden');
        });
        $('#bidia').click(function(){
            $('.dimain').removeAttr('hidden');
            $('.bidimen').attr('hidden','hidden');
            $('#arbi').removeAttr('hidden');
            $('.vuel').attr('hidden','hidden');
            $('.texa').attr('hidden','hidden');
        $('#artri').removeAttr('hidden');
        $('#brtri').removeAttr('hidden');
        });
        $('#vuel1').click(function(){
            $('.dimain').removeAttr('hidden');
            $('.bidimen').attr('hidden','hidden');
            $('#arbi').removeAttr('hidden');
            $('.vuel').attr('hidden','hidden');
            $('.texa').attr('hidden','hidden');
        $('#artri').removeAttr('hidden');
        $('#brtri').removeAttr('hidden');
        });
        $('#bidic').click(function(){
            $('.dimain').removeAttr('hidden');
            $('.bidimen').attr('hidden','hidden');
            $('#arbi').removeAttr('hidden');
            $('.texa').attr('hidden','hidden');
        $('#artri').removeAttr('hidden');
        $('#brtri').removeAttr('hidden');
        $('.vuel').attr('hidden','hidden');
        });


    $("#tridi0").mouseenter(function(){
        $("#tridib").removeAttr("hidden");
        $("#artri1").removeAttr("hidden");
        $("#brtri1").removeAttr("hidden");
        });
    $("#tridi0").mouseleave(function(){
        $("#tridib").attr('hidden','hidden');
        $("#artri1").attr('hidden','hidden');
        $("#brtri1").attr('hidden','hidden');
    });
    $("#tridib").click(function(){
        $('.tridimen').removeAttr('hidden');
        $('.dimain').attr('hidden','hidden');
        $('.disec').attr('hidden','hidden');
        $('#vuel2').removeAttr('hidden');
        $('#tex4').removeAttr('hidden');
    });
    $("#tridi0").click(function(){
        $('.tridimen').removeAttr('hidden');
        $('.dimain').attr('hidden','hidden');
        $('.disec').attr('hidden','hidden');
        $('#vuel2').removeAttr('hidden');
        $('#tex4').removeAttr('hidden');
    });
    $("#artri").click(function(){
        $('.tridimen').removeAttr('hidden');
        $('.dimain').attr('hidden','hidden');
        $('.disec').attr('hidden','hidden');
        $('#vuel2').removeAttr('hidden');
        $('#tex4').removeAttr('hidden');
    });
    $("#brtri").click(function(){
        $('.tridimen').removeAttr('hidden');
        $('.dimain').attr('hidden','hidden');
        $('.disec').attr('hidden','hidden');
        $('#vuel2').removeAttr('hidden');
        $('#tex4').removeAttr('hidden');
    });
    $("#tridia2").mouseenter(function(){
        $('.tridic').removeAttr('hidden');
    });
    $("#tridia1").mouseenter(function(){
        $('.tridic').removeAttr('hidden');
    });
    $('#tridia2').mouseleave(function(){
        $(".tridic").attr('hidden','hidden');
        });
        $("#tridia1").mouseleave(function(){
            $(".tridic").attr('hidden','hidden');
    });
    $('#tridia1').click(function(){
        $('.dimain').removeAttr('hidden');
        $('.tridimen').attr('hidden','hidden');
        $('#arbi').removeAttr('hidden');
        $('#artri').removeAttr('hidden');
        $('#brtri').removeAttr('hidden');
        $('.vuel').attr('hidden','hidden');
        $('#tex4').attr('hidden','hidden');
    });
    $('#tridia2').click(function(){
        $('.dimain').removeAttr('hidden');
        $('.tridimen').attr('hidden','hidden');
        $('#arbi').removeAttr('hidden');
        $('#artri').removeAttr('hidden');
        $('#brtri').removeAttr('hidden');
        $('.vuel').attr('hidden','hidden');
        $('#tex4').attr('hidden','hidden');
    });
    $('#tridic1').click(function(){
        $('.dimain').removeAttr('hidden');
        $('.tridimen').attr('hidden','hidden');
        $('#arbi').removeAttr('hidden');
        $('#artri').removeAttr('hidden');
        $('#brtri').removeAttr('hidden');
        $('.vuel').attr('hidden','hidden');
        $('#tex4').attr('hidden','hidden');
    });
    $('#tridic2').click(function(){
        $('.dimain').removeAttr('hidden');
        $('.tridimen').attr('hidden','hidden');
        $('#arbi').removeAttr('hidden');
        $('#artri').removeAttr('hidden');
        $('#brtri').removeAttr('hidden');
        $('.vuel').attr('hidden','hidden');
        $('#tex4').attr('hidden','hidden');
    });
    $('#vuel2').click(function(){
        $('.dimain').removeAttr('hidden');
        $('.tridimen').attr('hidden','hidden');
        $('#arbi').removeAttr('hidden');
        $('#artri').removeAttr('hidden');
        $('#brtri').removeAttr('hidden');
        $('.vuel').attr('hidden','hidden');
        $('#tex4').attr('hidden','hidden');
    });

    });